---
title: "Análisis transcriptómico de gal-3"
author: "Miriam Valdayo Camacho"
date: "2025-03-30"
output: html_document
---


Cargamos los paquetes:
```{r}
library(oligo)

ko_mouses_6m <- list.files(path = "6m/CEL/ko", pattern = "[Cc][Ee][Ll]$", full.names = TRUE)
wt_mouses_6m <- list.files(path = "6m/CEL/wt", pattern = "[Cc][Ee][Ll]$", full.names = TRUE)
ko_mouses_24 <- list.files(path = "24m/CEL/ko", pattern = "[Cc][Ee][Ll]$", full.names = TRUE)
wt_mouses_24 <- list.files(path = "24m/CEL/wt", pattern = "[Cc][Ee][Ll]$", full.names = TRUE)

# unimos todos los archivos
celFiles <- c(ko_mouses_6m, wt_mouses_6m, ko_mouses_24, wt_mouses_24)


# leemos los datos
microarray.raw.data <- read.celfiles(celFiles)

annotation(microarray.raw.data) #esto nos da el tipo de array

```


```{r}
#BiocManager::install("clariomsmousetranscriptcluster.db")
#BiocManager::install("AnnotationDbi")
library(clariomsmousetranscriptcluster.db)
library(AnnotationDbi)

```


*Control de calidad*

```{r}
# como podemos hacerlo de varias formas, por aquí se generan las imágenes pero vamos a usar un paquete más completo después
# por ello no mostramos todas 
image(microarray.raw.data[,1],col=rainbow(100))
image(microarray.raw.data[,2],col=rainbow(100))

boxplot(microarray.raw.data, col = rainbow(length(sampleNames(microarray.raw.data))), las=2, ylab="Fluorescence (R.U.)")
hist(as.vector(exprs(microarray.raw.data)), breaks=100, col="grey", main="Histograma de intensidades")

```

```{r}
library(arrayQualityMetrics)
arrayQualityMetrics(expressionset = microarray.raw.data,
                    outdir = "QC_Report_Crudos",
                    force = TRUE,
                    do.logtransform = TRUE)

```


AQUI TENGO QUE METER LOS REPORTES.



Ahora sí, vamos a preprocesar los datos:

```{r}
microarray.processed.data <- rma(microarray.raw.data)

boxplot(microarray.processed.data,col=rainbow(8),las=2,ylab="Fluorescence (R.U.)")


expression.level <- exprs(microarray.processed.data)
head(expression.level)
dim(expression.level)


sampleID <- c("ko1_6m","ko2_6m","ko3_6m","ko4_6m",
              "wt1_6m","wt2_6m","wt3_6m","wt4_6m",
              "ko1_24m","ko2_24m","ko3_24m","ko4_24m",
              "wt1_24m","wt2_24m","wt3_24m")
colnames(expression.level) <- sampleID
head(expression.level)


# réplicas KO a 6 meses
plot(expression.level[,"ko1_6m"], expression.level[,"ko2_6m"],
     pch = 19, col = "grey", cex = 0.5,
     xlab = "KO 6m - réplica 1", ylab = "KO 6m - réplica 2")
text(x = 4, y = 12,
     labels = paste0("cor = ", 
                     round(100 * cor(expression.level[,"ko1_6m"], expression.level[,"ko2_6m"]), 2), "%"))

# réplicas KO a 24 meses
plot(expression.level[,"ko1_24m"], expression.level[,"ko2_24m"],
     pch = 19, col = "grey", cex = 0.5,
     xlab = "KO 24m - réplica 1", ylab = "KO 24m - réplica 2")

text(x = 4, y = 12,
     labels = paste0("cor = ", 
                     round(100 * cor(expression.level[,"ko1_24m"], expression.level[,"ko2_24m"]), 2), "%"))

```


ANÁLISIS DE COMPONENTES PRINCIPALES

```{r}
library(FactoMineR)
library(factoextra)

pca.gene.expression <- data.frame(colnames(expression.level),t(expression.level))
colnames(pca.gene.expression)[1] <- "Sample"

# Realiza el PCA con variable cualitativa suplementaria
res.pca <- PCA(pca.gene.expression, graph = FALSE, scale.unit = TRUE, quali.sup = 1)

# Análisis de clusters jerárquicos sobre el resultado del PCA
res.hcpc <- HCPC(res.pca, graph = FALSE)

# Dendrograma 
fviz_dend(res.hcpc, 
          k = 4,
          cex = 0.75,                          # Tamaño de las etiquetas
          palette = "jco",                     # Paleta de colores
          rect = TRUE, 
          rect_fill = TRUE,                    # Rellenar los rectángulos
          rect_border = "jco",                 # Color del borde del rectángulo
          type = "rectangle",
          labels_track_height = 1400           # Altura de la pista de etiquetas (usa escala más realista)
)

```


Colapsamos las réplicas en un único vector.

```{r}

ko_6m <- (expression.level[,"ko1_6m"] + expression.level[,"ko2_6m"] + expression.level[,"ko3_6m"] + expression.level[,"ko4_6m"])/4
wt_6m <- (expression.level[,"wt1_6m"] + expression.level[,"wt2_6m"] + expression.level[,"wt3_6m"] + expression.level[,"wt4_6m"])/4
ko_24m <- (expression.level[,"ko1_24m"] + expression.level[,"ko2_24m"] + expression.level[,"ko3_24m"] + expression.level[,"ko4_24m"])/4
wt_24m <- (expression.level[,"wt1_24m"] + expression.level[,"wt2_24m"] + expression.level[,"wt3_24m"])/3


mean.expression <- matrix(c(ko_6m,wt_6m,ko_24m,wt_24m),ncol=4)
conditions.id <- c("ko_6m","wt_6m","ko_24m","wt_24m")
rownames(mean.expression) <- names(ko_6m)
colnames(mean.expression) <- conditions.id
head(mean.expression)


plot(ko_6m,wt_6m,xlab="Ko 6 meses",ylab="WT 6 meses",pch=19,cex=0.5)

```

A continuación hacemos contrastes de hipótesis:

```{r}

library(limma)


experimental.design <- model.matrix(~ -1+factor(c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4)))
colnames(experimental.design) <- c("ko_6m","wt_6m","ko_24m","wt_24m")
experimental.design



dim(expression.level)
dim(experimental.design)


linear.fit <- lmFit(expression.level, experimental.design)

contrast.matrix <- makeContrasts(
  ko_6m - wt_6m,
  ko_24m - ko_6m,
  wt_24m - wt_6m,
  ko_24m - wt_24m,  # este es el nuevo contraste
  levels = c("ko_6m", "wt_6m", "ko_24m", "wt_24m")
)



dim(linear.fit$coefficients)
dim(contrast.matrix)

contrast.linear.fit <- contrasts.fit(linear.fit, contrast.matrix)
contrast.results <- eBayes(contrast.linear.fit)

```
*KO 6m vs WT 6m*

```{r}

# 1. Extraer tabla y logFC
ko_6m_vs_wt_6m <- topTable(contrast.results, number = 29129, coef = 1, sort.by = "logFC")
fold.change.ko_6m_vs_wt_6m <- ko_6m_vs_wt_6m$logFC
genes.ids.ko_6m_vs_wt_6m <- rownames(ko_6m_vs_wt_6m)  # Transcript cluster IDs

# 2. Filtrar genes activados y reprimidos
activated_ids_ko_6m_wt_6m <- genes.ids.ko_6m_vs_wt_6m[fold.change.ko_6m_vs_wt_6m > 0.5]
repressed_ids_ko_6m_wt_6m <- genes.ids.ko_6m_vs_wt_6m[fold.change.ko_6m_vs_wt_6m < -0.5]

"TC1400000513.mm.2" %in% activated_ids_ko_6m_wt_6m
"TC1400000513.mm.2" %in% repressed_ids_ko_6m_wt_6m

# 3. Mapear PROBEID → ENTREZID usando el paquete oficial
library(clariomsmousetranscriptcluster.db)
library(AnnotationDbi)
library(dplyr)

# Obtener todos los mapeos posibles
mapped <- AnnotationDbi::select(clariomsmousetranscriptcluster.db,
                                keys = activated_ids_ko_6m_wt_6m,
                                columns = "ENTREZID",
                                keytype = "PROBEID")

# Filtrar duplicados y NAs
mapped_unique <- mapped %>%
  filter(!is.na(ENTREZID)) %>%
  distinct(PROBEID, .keep_all = TRUE)

# Obtener ENTREZIDs únicos
entrez_ids_activated <- unique(mapped_unique$ENTREZID)

# 4. enrichGO con ENTREZID únicos
library(clusterProfiler)
library(org.Mm.eg.db)

ego_ko_6m_vs_wt_6m <- enrichGO(
  gene         = entrez_ids_activated,
  OrgDb        = org.Mm.eg.db,
  keyType      = "ENTREZID",
  ont          = "BP",
  pAdjustMethod= "BH",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.1,
  readable     = TRUE
)

# 5. Visualización
barplot(ego_ko_6m_vs_wt_6m, showCategory = 20)


```


*WT 24m vs KO 24m*

```{r}

# 1. Obtener tabla de resultados
ko_24m_vs_wt_24m <- topTable(contrast.results, number = 29129, coef = 4, sort.by = "logFC")
fold.change.ko_24m_vs_wt_24m <- ko_24m_vs_wt_24m$logFC
genes.ids.ko_24m_vs_wt_24m <- rownames(ko_24m_vs_wt_24m)  # Transcript Cluster IDs

# 2. Filtrar genes activados y reprimidos
activated_ids_ko_24m_wt_24m <- genes.ids.ko_24m_vs_wt_24m[fold.change.ko_24m_vs_wt_24m > 0.5]
repressed_ids_ko_24m_wt_24m <- genes.ids.ko_24m_vs_wt_24m[fold.change.ko_24m_vs_wt_24m < -0.5]
"TC1400000513.mm.2" %in% activated_ids_ko_24m_wt_24m
"TC1400000513.mm.2" %in% repressed_ids_ko_24m_wt_24m


# 3. Cargar paquetes de anotación y enriquicimiento
library(clariomsmousetranscriptcluster.db)
library(AnnotationDbi)
library(clusterProfiler)
library(org.Mm.eg.db)
library(dplyr)

# 4. Mapear Transcript Cluster IDs → ENTREZID
mapped_24m <- AnnotationDbi::select(clariomsmousetranscriptcluster.db,
                                    keys = activated_ids_ko_24m_wt_24m,
                                    columns = "ENTREZID",
                                    keytype = "PROBEID")

# 5. Filtrar duplicados y NAs
mapped_unique_24m <- mapped_24m %>%
  filter(!is.na(ENTREZID)) %>%
  distinct(PROBEID, .keep_all = TRUE)

# 6. Extraer ENTREZ IDs únicos
entrez_ids_activated_24m <- unique(mapped_unique_24m$ENTREZID)
"Lgals3" %in% entrez_ids_activated_24m
# 7. enrichGO con ENTREZIDs (ratón)
ego_ko_24m_vs_wt_24m <- enrichGO(
  gene         = entrez_ids_activated_24m,
  OrgDb        = org.Mm.eg.db,
  keyType      = "ENTREZID",
  ont          = "BP",
  pAdjustMethod= "BH",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.1,
  readable     = TRUE
)

# 8. Visualización
barplot(ego_ko_24m_vs_wt_24m, showCategory = 10)


```



```{r}

# 4. Mapear Transcript Cluster IDs → ENTREZID
mapped_24m <- AnnotationDbi::select(clariomsmousetranscriptcluster.db,
                                    keys = repressed_ids_ko_24m_wt_24m,
                                    columns = "ENTREZID",
                                    keytype = "PROBEID")

# 5. Filtrar duplicados y NAs
mapped_unique_24m <- mapped_24m %>%
  filter(!is.na(ENTREZID)) %>%
  distinct(PROBEID, .keep_all = TRUE)

# 6. Extraer ENTREZ IDs únicos
entrez_ids_repressed_24m <- unique(mapped_unique_24m$ENTREZID)
"Lgals3" %in% entrez_ids_activated_24m
# 7. enrichGO con ENTREZIDs (ratón)
ego_ko_24m_vs_wt_24m_repressed <- enrichGO(
  gene         = entrez_ids_repressed_24m,
  OrgDb        = org.Mm.eg.db,
  keyType      = "ENTREZID",
  ont          = "BP",
  pAdjustMethod= "BH",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.1,
  readable     = TRUE
)

# 8. Visualización
barplot(ego_ko_24m_vs_wt_24m_repressed, showCategory = 10)

```

*KO 24m vs KO 6m*

```{r}

# 1. Obtener resultados del contraste 24m vs 6m (solo KO)
ko_24m_vs_ko_6m <- topTable(contrast.results, number = 29129, coef = 2, sort.by = "logFC")
fold.change.ko_24m_vs_ko_6m <- ko_24m_vs_ko_6m$logFC
genes.ids.ko_24m_vs_ko_6m <- rownames(ko_24m_vs_ko_6m)  # Transcript Cluster IDs

# 2. Filtrar genes activados y reprimidos
activated_ids_ko_24m_ko_6m <- genes.ids.ko_24m_vs_ko_6m[fold.change.ko_24m_vs_ko_6m > 0.5]
repressed_ids_ko_24m_ko_6m <- genes.ids.ko_24m_vs_ko_6m[fold.change.ko_24m_vs_ko_6m < -0.5]
"TC1400000513.mm.2" %in% activated_ids_ko_24m_ko_6m
"TC1400000513.mm.2" %in% repressed_ids_ko_24m_ko_6m
# 3. Cargar paquetes
library(clariomsmousetranscriptcluster.db)
library(AnnotationDbi)
library(clusterProfiler)
library(org.Mm.eg.db)
library(dplyr)

# 4. Mapear PROBEID (Transcript Cluster ID) → ENTREZID
mapped_ko_24m_ko_6m <- AnnotationDbi::select(clariomsmousetranscriptcluster.db,
                                             keys = activated_ids_ko_24m_ko_6m,
                                             columns = "ENTREZID",
                                             keytype = "PROBEID")

# 5. Limpiar: eliminar NAs y duplicados
mapped_unique_ko_24m_ko_6m <- mapped_ko_24m_ko_6m %>%
  filter(!is.na(ENTREZID)) %>%
  distinct(PROBEID, .keep_all = TRUE)

# 6. Extraer ENTREZ IDs únicos
entrez_ids_activated_ko_24m_ko_6m <- unique(mapped_unique_ko_24m_ko_6m$ENTREZID)

# 7. enrichGO con ENTREZID
ego_ko_24m_vs_ko_6m <- enrichGO(
  gene         = entrez_ids_activated_ko_24m_ko_6m,
  OrgDb        = org.Mm.eg.db,
  keyType      = "ENTREZID",
  ont          = "BP",
  pAdjustMethod= "BH",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.1,
  readable     = TRUE
)

# 8. Visualización
barplot(ego_ko_24m_vs_ko_6m, showCategory = 10)


```


*WT 24m vs WT 6m*

```{r}

# 1. Obtener tabla de resultados del contraste WT 24m vs WT 6m
wt_24m_vs_wt_6m <- topTable(contrast.results, number = 29129, coef = 3, sort.by = "logFC")
fold.change.wt_24m_vs_wt_6m <- wt_24m_vs_wt_6m$logFC
genes.ids.wt_24m_vs_wt_6m <- rownames(wt_24m_vs_wt_6m)  # Transcript Cluster IDs

# 2. Filtrar genes activados y reprimidos
activated_ids_wt_24m_vs_wt_6m <- genes.ids.wt_24m_vs_wt_6m[fold.change.wt_24m_vs_wt_6m > 0.5]
repressed_ids_wt_24m_vs_wt_6m <- genes.ids.wt_24m_vs_wt_6m[fold.change.wt_24m_vs_wt_6m < -0.5]

"TC1400000513.mm.2" %in% activated_ids_wt_24m_vs_wt_6m
"TC1400000513.mm.2" %in% repressed_ids_wt_24m_vs_wt_6m
# 3. Cargar paquetes
library(clariomsmousetranscriptcluster.db)
library(AnnotationDbi)
library(clusterProfiler)
library(org.Mm.eg.db)
library(dplyr)

# 4. Mapear IDs del array → ENTREZID
mapped_wt_24m_vs_wt_6m <- AnnotationDbi::select(clariomsmousetranscriptcluster.db,
                                                keys = activated_ids_wt_24m_vs_wt_6m,
                                                columns = "ENTREZID",
                                                keytype = "PROBEID")

# 5. Limpiar: eliminar NAs y duplicados
mapped_unique_wt_24m_vs_wt_6m <- mapped_wt_24m_vs_wt_6m %>%
  filter(!is.na(ENTREZID)) %>%
  distinct(PROBEID, .keep_all = TRUE)

# 6. Obtener ENTREZ IDs únicos
entrez_ids_wt_24m_vs_wt_6m <- unique(mapped_unique_wt_24m_vs_wt_6m$ENTREZID)
# 7. enrichGO
ego_wt_24m_vs_wt_6m <- enrichGO(
  gene         = entrez_ids_wt_24m_vs_wt_6m,
  OrgDb        = org.Mm.eg.db,
  keyType      = "ENTREZID",
  ont          = "BP",
  pAdjustMethod= "BH",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.1,
  readable     = TRUE
)

# 8. Visualización
barplot(ego_wt_24m_vs_wt_6m, showCategory = 10)



```

```{r}
# 4. Mapear IDs del array → ENTREZID
mapped_wt_24m_vs_wt_6m <- AnnotationDbi::select(clariomsmousetranscriptcluster.db,
                                                keys = repressed_ids_wt_24m_vs_wt_6m,
                                                columns = "ENTREZID",
                                                keytype = "PROBEID")

# 5. Limpiar: eliminar NAs y duplicados
mapped_unique_wt_24m_vs_wt_6m_repressed <- mapped_wt_24m_vs_wt_6m %>%
  filter(!is.na(ENTREZID)) %>%
  distinct(PROBEID, .keep_all = TRUE)

# 6. Obtener ENTREZ IDs únicos
entrez_ids_wt_24m_vs_wt_6m <- unique(mapped_unique_wt_24m_vs_wt_6m_repressed$ENTREZID)
# 7. enrichGO
ego_wt_24m_vs_wt_6m <- enrichGO(
  gene         = entrez_ids_wt_24m_vs_wt_6m,
  OrgDb        = org.Mm.eg.db,
  keyType      = "ENTREZID",
  ont          = "BP",
  pAdjustMethod= "BH",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.1,
  readable     = TRUE
)

# 8. Visualización
barplot(ego_wt_24m_vs_wt_6m, showCategory = 10)


```


Esto me da la traducción de como se llama la galectina 3 en mi entrezid.
```{r}
AnnotationDbi::select(clariomsmousetranscriptcluster.db,
                      keys = "TC1400000513.mm.2",
                      columns = "SYMBOL",
                      keytype = "PROBEID")
```


```{r}
symbol_to_probes <- AnnotationDbi::select(clariomsmousetranscriptcluster.db,
                                          keys = "Lgals3",
                                          columns = c("PROBEID", "ENTREZID"),
                                          keytype = "SYMBOL")
symbol_to_probes

```














